project:
  type: website

website:
  title: "siberpro"
  description: "di kelas ini kamu akan belajar tentang pembuatan webflow secara mendasar, mulai dari apa itu html dan css, membuat halaman web sederhana dengan html dan css dan akan dilanjutkan dengan membuat landing page interactive dengan webflow"
  navbar:
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SIBERPRO-OFFICIAL
      - icon: twitter
        href: https://twitter.com/siberpro
      - icon: linkedin
        href: https://linkedin.com/in/siberpro
  sidebar:
    style: floating
    contents:
      - text: Daftar Isi
      - section: "Hari #1"
        contents:
          - Hari 1/git_for_beginner.qmd
          - Hari 1/html_css_for_beginner.qmd
          - Hari 1/landing_page_with_webflow.qmd
        
  back-to-top-navigation: true
  reader-mode: true
format:
  html:
    theme: sandstone
    css: styles.css
execute:
  freeze: auto
